# PS >= 1.7.4 FO configuration
imports:
  - { resource: ../services/sf34.yml }
  - { resource: ../services/common_front.yml }

services:
  _defaults:
    public: false

  inpost.izi.hook_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: [ container.service_locator ]
    arguments:
      - actionObjectCartDeleteBefore: '@izi\prestashop\Hook\Common\ActionCartDeleteBefore'
        actionObjectCartUpdateAfter: '@izi\prestashop\Hook\Common\ActionCartUpdateAfter'
        actionObjectInPostShipmentModelAddAfter: '@izi\prestashop\Hook\Common\ActionShipmentAddAfter'
        actionObjectInPostShipmentModelUpdateBefore: '@izi\prestashop\Hook\Common\ActionShipmentUpdateBefore'
        actionObjectInPostShipmentModelUpdateAfter: '@izi\prestashop\Hook\Common\ActionShipmentUpdateAfter'
        actionValidateOrder: '@izi\prestashop\Hook\Common\ActionValidateOrder'
        actionOrderStatusPostUpdate: '@izi\prestashop\Hook\Common\ActionOrderStatusPostUpdate'
        actionObjectOrderAddAfter: '@izi\prestashop\Hook\Common\ActionObjectOrderAddAfter'
        actionObjectOrderUpdateBefore: '@izi\prestashop\Hook\Common\ActionObjectOrderUpdateBefore'
        actionObjectOrderUpdateAfter: '@izi\prestashop\Hook\Common\ActionObjectOrderUpdateAfter'
        actionObjectOrderCartRuleAddBefore: '@izi\prestashop\Hook\Common\ActionObjectOrderCartRuleAddBefore'
        actionAjaxDieCartControllerdisplayAjaxUpdateBefore: '@izi\prestashop\Hook\Front\ActionCartControllerAjaxUpdateResponse'
        actionFrontControllerSetMedia: '@izi\prestashop\Hook\Front\ActionFrontControllerSetMedia'
        actionEmailSendBefore: '@izi\prestashop\Hook\Common\ActionEmailSendBefore'
        displayHeader: '@izi\prestashop\Hook\Front\DisplayHeader'
        paymentOptions: '@izi\prestashop\Hook\Front\ActionGetPaymentOptions'
        displayOrderConfirmation: '@izi\prestashop\Hook\Front\DisplayOrderConfirmation'
        displayIziThankYou: '@izi\prestashop\Hook\Front\DisplayIziThankYou'
        displayPaymentReturn: '@izi\prestashop\Hook\Front\DisplayPaymentReturn'
        displayProductActions: '@izi\prestashop\Hook\Front\DisplayProductActions'
        displayProductAdditionalInfo: '@izi\prestashop\Hook\Front\DisplayProductAdditionalInfo'
        displayIziProductButton: '@izi\prestashop\Hook\Front\DisplayIziProductButton'
        displayExpressCheckout: '@izi\prestashop\Hook\Front\DisplayExpressCheckout'
        displayShoppingCart: '@izi\prestashop\Hook\Front\DisplayShoppingCart'
        displayShoppingCartFooter: '@izi\prestashop\Hook\Front\DisplayShoppingCartFooter'
        displayCheckoutSummaryTop: '@izi\prestashop\Hook\Front\DisplayCheckoutSummaryTop'
        displayCustomerAccountFormTop: '@izi\prestashop\Hook\Front\DisplayCustomerAccountFormTop'
        displayCustomerLoginFormAfter: '@izi\prestashop\Hook\Front\DisplayCustomerLoginFormAfter'
        displayIziCartPreviewButton: '@izi\prestashop\Hook\Front\DisplayIziCartPreviewButton'
        displayIziCheckoutButton: '@izi\prestashop\Hook\Front\DisplayIziCheckoutButton'
        displayPDFInvoice: '@izi\prestashop\Hook\Common\DisplayPDFInvoice'
        # InPost discounts
        actionApplyCartRule: '@izi\prestashop\Hook\Common\CartRule\ActionApplyCartRule'
        actionGetCartRuleContextualValue: '@izi\prestashop\Hook\Common\CartRule\ActionGetCartRuleContextualValue'
        actionValidateCartRule: '@izi\prestashop\Hook\Common\CartRule\ActionValidateCartRule'
        # products
        actionObjectProductDeleteBefore: '@izi\prestashop\Hook\Common\Product\ActionProductDeleteBefore'
        actionObjectProductDeleteAfter: '@izi\prestashop\Hook\Common\Product\ActionProductDeleteAfter'
        actionObjectProductUpdateAfter: '@izi\prestashop\Hook\Common\Product\ActionProductUpdateAfter'
        actionObjectCombinationDeleteBefore: '@izi\prestashop\Hook\Common\Product\ActionCombinationDeleteBefore'
        actionObjectCombinationDeleteAfter: '@izi\prestashop\Hook\Common\Product\ActionCombinationDeleteAfter'
        actionObjectCombinationUpdateAfter: '@izi\prestashop\Hook\Common\Product\ActionCombinationUpdateAfter'
        actionObjectImageAddAfter: '@izi\prestashop\Hook\Common\Product\ActionImageAddAfter'
        actionObjectImageDeleteAfter: '@izi\prestashop\Hook\Common\Product\ActionImageDeleteAfter'
        actionObjectSpecificPriceAddAfter: '@izi\prestashop\Hook\Common\Product\ActionSpecificPriceAddAfter'
        actionObjectSpecificPriceUpdateAfter: '@izi\prestashop\Hook\Common\Product\ActionSpecificPriceUpdateAfter'
        actionObjectSpecificPriceDeleteAfter: '@izi\prestashop\Hook\Common\Product\ActionSpecificPriceDeleteAfter'
        actionUpdateQuantity: '@izi\prestashop\Hook\Common\Product\ActionUpdateQuantity'

  inpost.izi.basket_event_handler_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: [ container.service_locator ]
    arguments:
      - PRODUCTS_QUANTITY: '@izi\prestashop\MerchantApi\Handler\Basket\ProductsQuantityEventHandler'
        PROMO_CODES: '@izi\prestashop\MerchantApi\Handler\Basket\PromoCodesEventHandler'
        RELATED_PRODUCTS: '@izi\prestashop\MerchantApi\Handler\Basket\RelatedProductsEventHandler'

  izi\prestashop\CommandBus:
    class: izi\prestashop\CommandBus
    arguments:
      - '@inpost.izi.command_handler_locator'

  inpost.izi.command_handler_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: [ container.service_locator ]
    arguments:
      - izi\prestashop\Command\UnbindBasketCommand: '@izi\prestashop\Handler\UnbindBasketHandlerInterface'
        izi\prestashop\Command\UpdateOrderTrackingNumbersCommand: '@izi\prestashop\Handler\UpdateOrderTrackingNumbersHandlerInterface'
        izi\prestashop\Command\UpdateOrderStatusCommand: '@izi\prestashop\Handler\UpdateOrderStatusHandlerInterface'
        izi\prestashop\Command\UpdateOrderAddressDeliveryCommand: '@izi\prestashop\Handler\UpdateOrderAddressDeliveryHandlerInterface'
        izi\prestashop\Command\UpdateBasketCommand: '@izi\prestashop\Handler\UpdateBasketHandlerInterface'
        izi\prestashop\Command\GetBasketBindingKeyCommand: '@izi\prestashop\Handler\GetBasketBindingKeyHandlerInterface'
        izi\prestashop\Command\GetOrderConfirmationUrlCommand: '@izi\prestashop\Handler\GetOrderConfirmationUrlHandlerInterface'
        izi\prestashop\Command\GetProductWidgetCommand: '@izi\prestashop\Handler\GetProductWidgetHandlerInterface'
        izi\prestashop\MerchantApi\Command\ConfirmBasketBindingCommand: '@izi\prestashop\MerchantApi\Handler\ConfirmBasketBindingHandlerInterface'
        izi\prestashop\MerchantApi\Command\DeleteBasketBindingCommand: '@izi\prestashop\MerchantApi\Handler\DeleteBasketBindingHandlerInterface'
        izi\prestashop\MerchantApi\Command\GetBasketCommand: '@izi\prestashop\MerchantApi\Handler\GetBasketHandlerInterface'
        izi\prestashop\MerchantApi\Command\UpdateBasketCommand: '@izi\prestashop\MerchantApi\Handler\UpdateBasketHandlerInterface'
        izi\prestashop\MerchantApi\Command\GetProductsCommand: '@izi\prestashop\MerchantApi\Handler\GetProductsHandlerInterface'
        izi\prestashop\MerchantApi\Command\AddProductToBasketCommand: '@izi\prestashop\MerchantApi\Handler\AddProductToBasketHandlerInterface'
        izi\prestashop\MerchantApi\Command\CreateOrderCommand: '@izi\prestashop\MerchantApi\Handler\CreateOrderHandlerInterface'
        izi\prestashop\MerchantApi\Command\GetOrderCommand: '@izi\prestashop\MerchantApi\Handler\GetOrderHandlerInterface'
        izi\prestashop\MerchantApi\Command\UpdateOrderCommand: '@izi\prestashop\MerchantApi\Handler\UpdateOrderHandlerInterface'
        izi\prestashop\MerchantApi\Command\Basket\CreateCartCommand: '@izi\prestashop\MerchantApi\Handler\Basket\CreateCartHandlerInterface'
        izi\prestashop\MerchantApi\Command\Basket\AddProductToCartCommand: '@izi\prestashop\MerchantApi\Handler\Basket\AddProductToCartHandlerInterface'
        izi\prestashop\MerchantApi\Command\Basket\IncrementCartQuantityCommand: '@izi\prestashop\MerchantApi\Handler\Basket\IncrementCartQuantityHandlerInterface'
        izi\prestashop\MerchantApi\Command\Order\UpdateCartMessageCommand: '@izi\prestashop\MerchantApi\Handler\Order\UpdateCartMessageHandlerInterface'
        izi\prestashop\HotProduct\Message\DeleteRemoteProductCommand: '@izi\prestashop\HotProduct\MessageHandler\DeleteRemoteProductHandlerInterface'
        izi\prestashop\HotProduct\Message\UpdateHotProductCommand: '@izi\prestashop\HotProduct\MessageHandler\UpdateHotProductHandlerInterface'
        izi\prestashop\Analytics\Command\UpdateCartAnalyticsCommand: '@izi\prestashop\Analytics\Handler\UpdateCartAnalyticsHandlerInterface'

  inpost.izi.widget_controller_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: [ container.service_locator ]
    arguments:
      - Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface: '@inpost.izi.security.authorization_checker'
        izi\prestashop\Cart\Storage\BasketIdStorageInterface: '@izi\prestashop\Cart\Storage\BasketIdStorageInterface'
