# PS >= 1.7.4 BO configuration
imports:
  - { resource: ../services/sf34.yml }
  - { resource: ../services/common_admin.yml }

parameters:
  container.autowiring.strict_mode: true

services:
  _defaults:
    public: false
    autowire: true
    bind:
      $context: '@inpost.izi.context'
      $assetsProviders: !tagged inpost.izi.admin_assets_provider
      $formFactory: '@=container.has("form.factory") ? service("form.factory") : service("inpost.izi.form_factory")'
      $debug: '%kernel.debug%'

  izi\prestashop\Hook\Admin\ActionAdminCartRuleSaveAfter:
    class: izi\prestashop\Hook\Admin\ActionAdminCartRuleSaveAfter

  izi\prestashop\Hook\Admin\ActionAdminCartRulesListingFieldsModifier:
    class: izi\prestashop\Hook\Admin\ActionAdminCartRulesListingFieldsModifier

  izi\prestashop\Hook\Admin\ActionAdminControllerSetMedia:
    class: izi\prestashop\Hook\Admin\ActionAdminControllerSetMedia

  izi\prestashop\Hook\Admin\ActionAdminInPostConfirmedShipmentsControllerAfter:
    class: izi\prestashop\Hook\Admin\ActionAdminInPostConfirmedShipmentsControllerAfter

  izi\prestashop\Hook\Admin\ActionAdminInPostConfirmedShipmentsControllerBefore:
    class: izi\prestashop\Hook\Admin\ActionAdminInPostConfirmedShipmentsControllerBefore

  izi\prestashop\Hook\Admin\DisplayAdminOrderSide:
    class: izi\prestashop\Hook\Admin\DisplayAdminOrderSide

  izi\prestashop\Hook\Admin\DisplayAdminOrderLeft:
    class: izi\prestashop\Hook\Admin\DisplayAdminOrderLeft

  izi\prestashop\Hook\Admin\DisplayBackOfficeHeader:
    class: izi\prestashop\Hook\Admin\DisplayBackOfficeHeader

  izi\prestashop\Hook\Admin\Product\ActionProductFormBuilderModifier:
    class: izi\prestashop\Hook\Admin\Product\ActionProductFormBuilderModifier

  izi\prestashop\Hook\Admin\Product\ActionAfterUpdateProductFormHandler:
    class: izi\prestashop\Hook\Admin\Product\ActionAfterUpdateProductFormHandler

  izi\prestashop\Hook\Legacy\Admin\Product\DisplayAdminProductsExtra:
    class: izi\prestashop\Hook\Legacy\Admin\Product\DisplayAdminProductsExtra

  izi\prestashop\Hook\Legacy\Admin\Product\DisplayAdminProductsOptionsStepBottom:
    class: izi\prestashop\Hook\Legacy\Admin\Product\DisplayAdminProductsOptionsStepBottom

  izi\prestashop\Hook\Legacy\Admin\Product\ActionAdminProductsSaveAfter:
    class: izi\prestashop\Hook\Legacy\Admin\Product\ActionAdminProductsSaveAfter

  izi\prestashop\CommandBus:
    class: izi\prestashop\CommandBus
    tags: [ container.service_subscriber ]

  izi\prestashop\Hook\HookExecutor:
    class: izi\prestashop\Hook\HookExecutor
    tags: [ container.service_subscriber ]
    arguments:
      $widget: '@inpost.izi.module'

  izi\prestashop\Form\FormFactoryFactory:
    class: izi\prestashop\Form\FormFactoryFactory

  inpost.izi.form_factory:
    class: Symfony\Component\Form\FormFactoryInterface
    factory: [ '@izi\prestashop\Form\FormFactoryFactory', create ]
    arguments:
      - '@inpost.izi.form_type_locator'
      - Symfony\Component\Form\Extension\Core\Type\FormType: ['@izi\prestashop\Form\TypeExtension\HelpTextExtension']

  inpost.izi.form_type_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags:
      - { name: container.service_locator }
    arguments:
      - izi\prestashop\Form\Type\CartRuleOptionsType: '@izi\prestashop\Form\Type\CartRuleOptionsType'
        izi\prestashop\Form\Type\ObjectModelType: '@izi\prestashop\Form\Type\ObjectModelType'
        izi\prestashop\Form\Type\EnumType: '@izi\prestashop\Form\Type\EnumType'
        izi\prestashop\ProductOptions\Form\ProductOptionsType: '@izi\prestashop\ProductOptions\Form\ProductOptionsType'
