# PS < 1.7.4 configuration
imports:
  - { resource: common.yml }
  - { resource: common_admin.yml }
  - { resource: common_front.yml }
  - { resource: sf28/cache.php }

parameters:
  inpost.izi.logs_dir: '%kernel.root_dir%/logs/inpost'

services:
  inpost.izi.event_dispatcher:
    class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
    public: false
    arguments:
      - '@service_container'

  izi\prestashop\CommandBus:
    class: izi\prestashop\CommandBus
    arguments:
      - '@inpost.izi.command_handler_locator'

  inpost.izi.command_handler_locator:
    class: izi\prestashop\DependencyInjection\ServiceLocator
    autowire: true
    tags:
      - { name: inpost.izi.service_locator, tag: inpost.izi.command_handler, index_by: command_class, default_index_method: getHandledCommandClass }

  izi\prestashop\Hook\HookExecutor:
    class: izi\prestashop\Hook\HookExecutor
    arguments:
      - '@inpost.izi.hook_locator'
      - '@inpost.izi.module'

  inpost.izi.hook_locator:
    class: izi\prestashop\DependencyInjection\ServiceLocator
    autowire: true
    tags:
      - { name: inpost.izi.service_locator, tag: inpost.izi.hook, index_by: hook_name, default_index_method: getHookName }

  inpost.izi.repository_locator:
    class: izi\prestashop\DependencyInjection\ServiceLocator
    autowire: true
    tags:
      - { name: inpost.izi.service_locator, tag: inpost.izi.model_repository, index_by: model_class }

  inpost.izi.basket_event_handler_locator:
    class: izi\prestashop\DependencyInjection\ServiceLocator
    autowire: true
    tags:
      - { name: inpost.izi.service_locator, tag: inpost.izi.basket_event_handler, index_by: event_type, default_index_method: getHandledEventType }

  izi\prestashop\Hook\Admin\ActionAdminCartRuleSaveAfter:
    class: izi\prestashop\Hook\Admin\ActionAdminCartRuleSaveAfter
    public: false
    tags:
      - { name: inpost.izi.hook }
    arguments:
      - '@inpost.izi.form_factory'
      - '@izi\prestashop\CommandBusInterface'

  izi\prestashop\Hook\Admin\ActionAdminCartRulesListingFieldsModifier:
    class: izi\prestashop\Hook\Admin\ActionAdminCartRulesListingFieldsModifier
    public: false
    tags:
      - { name: inpost.izi.hook }

  izi\prestashop\Hook\Admin\ActionAdminControllerSetMedia:
    class: izi\prestashop\Hook\Admin\ActionAdminControllerSetMedia
    public: false
    tags:
      - { name: inpost.izi.hook }
    arguments:
      - '@izi\prestashop\View\Asset\AdminAssetManager'
      - !tagged inpost.izi.admin_assets_provider

  izi\prestashop\Hook\Admin\DisplayBackOfficeHeader:
    class: izi\prestashop\Hook\Admin\DisplayBackOfficeHeader
    public: false
    tags:
      - { name: inpost.izi.hook }
    arguments:
      - '@inpost.izi.context'
      - '@izi\prestashop\Repository\CartRuleRepositoryInterface'
      - '@inpost.izi.form_factory'
      - '@izi\prestashop\View\Templating\RendererInterface'

  izi\prestashop\Hook\Admin\DisplayAdminOrderLeft:
    class: izi\prestashop\Hook\Admin\DisplayAdminOrderLeft
    public: false
    autowire: true
    tags:
      - { name: inpost.izi.hook }

  izi\prestashop\Hook\Admin\ActionAdminInPostConfirmedShipmentsControllerAfter:
    class: izi\prestashop\Hook\Admin\ActionAdminInPostConfirmedShipmentsControllerAfter
    public: false
    autowire: true
    tags:
      - { name: inpost.izi.hook }

  izi\prestashop\Hook\Admin\ActionAdminInPostConfirmedShipmentsControllerBefore:
    class: izi\prestashop\Hook\Admin\ActionAdminInPostConfirmedShipmentsControllerBefore
    public: false
    autowire: true
    tags:
      - { name: inpost.izi.hook }

  izi\prestashop\Hook\Legacy\Admin\Product\DisplayAdminProductsExtra:
    class: izi\prestashop\Hook\Legacy\Admin\Product\DisplayAdminProductsExtra
    public: false
    autowire: true
    tags:
      - { name: inpost.izi.hook }

  izi\prestashop\Hook\Legacy\Admin\Product\DisplayAdminProductsOptionsStepBottom:
    class: izi\prestashop\Hook\Legacy\Admin\Product\DisplayAdminProductsOptionsStepBottom
    public: false
    autowire: true
    tags:
      - { name: inpost.izi.hook }

  izi\prestashop\Hook\Legacy\Admin\Product\ActionAdminProductsSaveAfter:
    class: izi\prestashop\Hook\Legacy\Admin\Product\ActionAdminProductsSaveAfter
    public: false
    tags:
      - { name: inpost.izi.hook }
    arguments:
      - '@inpost.izi.form_factory'
      - '@izi\prestashop\CommandBusInterface'
      - '@izi\prestashop\Translation\LegacyTranslator'
      - '%kernel.debug%'

  inpost.izi.constraint_validator_locator:
    class: izi\prestashop\DependencyInjection\ServiceLocator
    autowire: true
    tags:
      - { name: inpost.izi.service_locator, tag: validator.constraint_validator }

  inpost.izi.gui_configuration_locator:
    class: izi\prestashop\DependencyInjection\ServiceLocator
    autowire: true
    tags:
      - { name: inpost.izi.service_locator, tag: inpost.izi.gui_configuration_dependency, index_by: key }

  izi\prestashop\Form\FormFactoryFactory:
    class: izi\prestashop\Form\FormFactoryFactory
    public: false
    arguments:
      - '@inpost.izi.validator'

  inpost.izi.form_factory:
    class: Symfony\Component\Form\FormFactoryInterface
    factory: [ '@izi\prestashop\Form\FormFactoryFactory', create ]
    public: false
    arguments:
      - '@inpost.izi.form_type_locator'
      -
        Symfony\Component\Form\Extension\Core\Type\ChoiceType: ['@izi\prestashop\Form\TypeExtension\ChoicesAsValuesTypeExtension']
        Symfony\Component\Form\Extension\Core\Type\FormType: ['@izi\prestashop\Form\TypeExtension\HelpTextExtension']

  inpost.izi.form_type_locator:
    class: izi\prestashop\DependencyInjection\ServiceLocator
    autowire: true
    tags:
      - { name: inpost.izi.service_locator, tag: form.type }

  izi\prestashop\Form\TypeExtension\ChoicesAsValuesTypeExtension:
    class: izi\prestashop\Form\TypeExtension\ChoicesAsValuesTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }

  inpost.izi.widget_controller_locator:
    class: izi\prestashop\DependencyInjection\ServiceLocator
    autowire: true
    tags:
      - { name: inpost.izi.service_locator, tag: inpost.izi.widget_controller_dependency, index_by: key }

  inpost.izi.inpost_discount.cart_rule_factory_locator:
    class: izi\prestashop\DependencyInjection\ServiceLocator
    autowire: true
    tags:
      - { name: inpost.izi.service_locator, tag: inpost.izi.inpost_discount.cart_rule_factory, index_by: discount_type, default_index_method: getDefaultDiscountType }

  inpost.izi.inpost_discount.applier_locator:
    class: izi\prestashop\DependencyInjection\ServiceLocator
    autowire: true
    tags:
      - { name: inpost.izi.service_locator, tag: inpost.izi.inpost_discount.applier, index_by: discount_type, default_index_method: getDefaultDiscountType }
