# PS >= 1.7.4 common FO/BO configuration
imports:
  - { resource: common.yml }

services:
  _defaults:
    public: false

  inpost.izi.repository_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags:
      - { name: container.service_locator }
    arguments:
      - Cart: '@inpost.izi.object_model.cart_repository'
        Country: '@inpost.izi.object_model.country_repository'
        Currency: '@izi\prestashop\ObjectModel\Repository\CurrencyRepository'
        Carrier: '@izi\prestashop\ObjectModel\Repository\CarrierRepository'
        CartRule: '@izi\prestashop\ObjectModel\Repository\CartRuleRepository'
        Combination: '@izi\prestashop\ObjectModel\Repository\CombinationRepository'
        Product: '@izi\prestashop\ObjectModel\Repository\ProductRepository'
        Configuration: '@izi\prestashop\ObjectModel\Repository\ConfigurationRepository'
        Hook: '@izi\prestashop\ObjectModel\Repository\HookRepository'
        Language: '@inpost.izi.object_model.language_repository'
        Order: '@inpost.izi.object_model.order_repository'
        OrderState: '@inpost.izi.object_model.order_state_repository'
        Shop: '@inpost.izi.object_model.shop_repository'
        InPostShipmentModel: '@izi\prestashop\ObjectModel\Repository\ShipmentRepository'

  inpost.izi.event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcherInterface
    factory: [ '@izi\prestashop\Event\EventDispatcherFactory', create ]

  inpost.izi.event_subscriber_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags:
      - { name: container.service_locator }
    arguments:
      - izi\prestashop\EventListener\ShipmentListener: '@izi\prestashop\EventListener\ShipmentListener'
        izi\prestashop\Cart\EventListener\SwitchBasketListener: '@?izi\prestashop\Cart\EventListener\SwitchBasketListener'
        izi\prestashop\Cart\EventListener\UpdateBasketListener: '@izi\prestashop\Cart\EventListener\UpdateBasketListener'
        izi\prestashop\EventListener\OrderListener: '@izi\prestashop\EventListener\OrderListener'
        izi\prestashop\Form\BasketAppClientProvider: '@?izi\prestashop\Form\BasketAppClientProvider'
        izi\prestashop\MerchantApi\EventListener\UpdateCartRulesListener: '@?izi\prestashop\MerchantApi\EventListener\UpdateCartRulesListener'
        izi\prestashop\HotProduct\EventListener\UpdateHotProductsListener: '@izi\prestashop\HotProduct\EventListener\UpdateHotProductsListener'
        izi\prestashop\EventListener\CreateShipmentListener: '@?izi\prestashop\EventListener\CreateShipmentListener'
        izi\prestashop\Mail\EventListener\ReplaceOrderNotificationRecipientListener: '@izi\prestashop\Mail\EventListener\ReplaceOrderNotificationRecipientListener'
        izi\prestashop\Mail\EventListener\AddDigitalDeliveryRecipientListener: '@izi\prestashop\Mail\EventListener\AddDigitalDeliveryRecipientListener'
        izi\prestashop\Analytics\EventListener\UpdateBasketAnalyticsListener: '@izi\prestashop\Analytics\EventListener\UpdateBasketAnalyticsListener'
        izi\prestashop\Extension\EventListener\ClearCacheListener: '@izi\prestashop\Extension\EventListener\ClearCacheListener'
        izi\prestashop\InPostDiscount\EventListener\ApplyDiscountsListener: '@izi\prestashop\InPostDiscount\EventListener\ApplyDiscountsListener'
        izi\prestashop\InPostDiscount\EventListener\ClearDiscountsListener: '@izi\prestashop\InPostDiscount\EventListener\ClearDiscountsListener'
        izi\prestashop\InPostDiscount\EventListener\CorrectOrderDiscountTaxesListener: '@izi\prestashop\InPostDiscount\EventListener\CorrectOrderDiscountTaxesListener'

  izi\prestashop\Event\EventDispatcherFactory:
    class: izi\prestashop\Event\EventDispatcherFactory
    arguments:
      - '@inpost.izi.event_subscriber_locator'

  inpost.izi.constraint_validator_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: [ container.service_locator ]
    arguments:
      - izi\prestashop\Validator\Cart\BindableValidator: '@?izi\prestashop\Validator\Cart\BindableValidator'
        izi\prestashop\Validator\Cart\HasProductsValidator: '@?izi\prestashop\Validator\Cart\HasProductsValidator'
        izi\prestashop\Validator\Cart\PaymentInCurrencyAvailableValidator: '@?izi\prestashop\Validator\Cart\PaymentInCurrencyAvailableValidator'
        izi\prestashop\Validator\Product\NotInRestrictedCategoryValidator: '@izi\prestashop\Validator\Product\NotInRestrictedCategoryValidator'
        izi\prestashop\Validator\Product\NotFromRestrictedManufacturerValidator: '@izi\prestashop\Validator\Product\NotFromRestrictedManufacturerValidator'
        izi\prestashop\Validator\Product\NotWithRestrictedAttributesValidator: '@izi\prestashop\Validator\Product\NotWithRestrictedAttributesValidator'
        izi\prestashop\Validator\Product\NotWithRestrictedFeaturesValidator: '@izi\prestashop\Validator\Product\NotWithRestrictedFeaturesValidator'
        izi\prestashop\Validator\Product\UnrestrictedValidator: '@izi\prestashop\Validator\Product\UnrestrictedValidator'

  inpost.izi.gui_configuration_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags: [ container.service_locator ]
    arguments:
      - validator: '@inpost.izi.validator'
        context: '@inpost.izi.shop_context'
        izi\prestashop\Repository\ProductRestrictionsRepositoryInterface: '@izi\prestashop\Repository\ProductRestrictionsRepositoryInterface'

  inpost.izi.inpost_discount.cart_rule_factory_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags:
      - container.service_locator
    arguments:
      - INPOST_SUBSCRIPTION: '@izi\prestashop\InPostDiscount\CartRule\Factory\InPostPlusCartRuleHandler'

  inpost.izi.inpost_discount.applier_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator
    tags:
      - container.service_locator
    arguments:
      - INPOST_SUBSCRIPTION: '@izi\prestashop\InPostDiscount\CartRule\Factory\InPostPlusCartRuleHandler'
