services:
  izi\prestashop\InPostDiscount\DiscountRepositoryInterface: '@izi\prestashop\InPostDiscount\CartRuleDiscountRepository'
  izi\prestashop\InPostDiscount\CartRuleDiscountRepository:
    class: izi\prestashop\InPostDiscount\CartRuleDiscountRepository
    public: false
    arguments:
      - '@izi\prestashop\Database\Connection'

  izi\prestashop\InPostDiscount\CartRule\CustomRuleRepositoryInterface: '@izi\prestashop\InPostDiscount\CartRule\ConfigurationCustomRuleRepository'
  izi\prestashop\InPostDiscount\CartRule\ConfigurationCustomRuleRepository:
    class: izi\prestashop\InPostDiscount\CartRule\ConfigurationCustomRuleRepository
    public: false
    arguments:
      - '@izi\prestashop\Configuration\Adapter\Configuration'
      - '@?database_connection'

  izi\prestashop\InPostDiscount\EventListener\ApplyDiscountsListener:
    class: izi\prestashop\InPostDiscount\EventListener\ApplyDiscountsListener
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      - '@izi\prestashop\InPostDiscount\DiscountHandlerInterface'
      - '@izi\prestashop\Event\EventDispatcherInterface'
      - '@inpost.izi.logger'

  izi\prestashop\InPostDiscount\EventListener\ClearDiscountsListener:
    class: izi\prestashop\InPostDiscount\EventListener\ClearDiscountsListener
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      - '@inpost.izi.context'
      - '@izi\prestashop\InPostDiscount\DiscountRepositoryInterface'
      - '@izi\prestashop\InPostDiscount\DiscountHandlerInterface'
      - '@inpost.izi.logger'

  izi\prestashop\InPostDiscount\EventListener\CorrectOrderDiscountTaxesListener:
    class: izi\prestashop\InPostDiscount\EventListener\CorrectOrderDiscountTaxesListener
    tags:
      - { name: kernel.event_subscriber }
    arguments:
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'
      - '@izi\prestashop\InPostDiscount\CartRule\Util\FeatureHelper'

  izi\prestashop\InPostDiscount\DiscountHandlerInterface: '@izi\prestashop\InPostDiscount\CartRuleDiscountHandler'
  izi\prestashop\InPostDiscount\CartRuleDiscountHandler:
    class: izi\prestashop\InPostDiscount\CartRuleDiscountHandler
    public: false
    arguments:
      - '@inpost.izi.context'
      - '@izi\prestashop\InPostDiscount\CartRule\Factory\CartRuleFactoryInterface'
      - '@izi\prestashop\InPostDiscount\CartRuleDiscountRepository'
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'

  izi\prestashop\InPostDiscount\CartRule\Factory\CartRuleFactoryInterface: '@izi\prestashop\InPostDiscount\CartRule\Factory\CartRuleFactory'
  izi\prestashop\InPostDiscount\CartRule\Factory\CartRuleFactory:
    class: izi\prestashop\InPostDiscount\CartRule\Factory\CartRuleFactory
    public: false
    arguments:
      - '@inpost.izi.inpost_discount.cart_rule_factory_locator'

  izi\prestashop\InPostDiscount\CartRule\DiscountApplierInterface: '@izi\prestashop\InPostDiscount\CartRule\DiscountApplier'
  izi\prestashop\InPostDiscount\CartRule\DiscountApplier:
    class: izi\prestashop\InPostDiscount\CartRule\DiscountApplier
    public: false
    arguments:
      - '@inpost.izi.inpost_discount.applier_locator'

  izi\prestashop\InPostDiscount\CartRule\Util\FeatureHelper:
    class: izi\prestashop\InPostDiscount\CartRule\Util\FeatureHelper
    public: false
    arguments:
      - '@inpost.izi.module'

  izi\prestashop\InPostDiscount\CartRule\Factory\InPostPlusCartRuleHandler:
    class: izi\prestashop\InPostDiscount\CartRule\Factory\InPostPlusCartRuleHandler
    public: false
    arguments:
      - '@izi\prestashop\ObjectModel\ObjectManagerInterface'
      - '@izi\prestashop\Configuration\PrestaShopConfiguration'
      - '@izi\prestashop\InPostDiscount\CartRule\Util\FeatureHelper'
      - '@izi\prestashop\InPostDiscount\CartRule\CustomRuleRepositoryInterface'
    tags:
      - { name: inpost.izi.inpost_discount.cart_rule_factory, discount_type: INPOST_SUBSCRIPTION }
      - { name: inpost.izi.inpost_discount.applier, discount_type: INPOST_SUBSCRIPTION }
