<?php

declare(strict_types=1);

namespace izi\prestashop\Analytics\Cookie;

use izi\prestashop\Analytics\Cookie\Factory\CookieFactoryInterface;
use izi\prestashop\Analytics\Cookie\Repository\CookieRepositoryInterface;
use Symfony\Component\HttpFoundation\Request;

if (!defined('_PS_VERSION_')) {
    exit;
}

class GenericClickIdExtractor implements CookieExtractorInterface, CookiePersisterInterface, CookieEraserInterface
{
    private const DEFAULT_OPTIONS = [
        'cookie_name' => null,
        'cookie_lifetime' => 3600,
    ];

    /**
     * @var CookieFactoryInterface
     */
    private $cookieFactory;

    /**
     * @var CookieRepositoryInterface
     */
    private $cookieRepository;

    /**
     * @var string
     */
    private $queryParameter;

    /**
     * @var array
     */
    private $options;

    /**
     * Recognized options:
     * - cookie_name: string - name of a temporary cookie that will be used to store the parameter value
     *                         if not provided, name will be generated by prefixing the query parameter name with "izi_"
     * - cookie_lifetime: int - cookie lifetime in seconds, 0 corresponds to a session cookie
     *
     * @param array<string, mixed> $options
     */
    public function __construct(CookieFactoryInterface $cookieFactory, CookieRepositoryInterface $cookieRepository, string $queryParam, array $options = [])
    {
        $this->cookieFactory = $cookieFactory;
        $this->cookieRepository = $cookieRepository;
        $this->queryParameter = $queryParam;
        $this->setOptions($options, $queryParam);
    }

    public function getParameterName(): string
    {
        return $this->queryParameter;
    }

    public function extract(Request $request): ?string
    {
        return $request->cookies->get($this->options['cookie_name']);
    }

    public function persist(Request $request): void
    {
        if (null === $value = $request->query->get($this->queryParameter)) {
            return;
        }

        $expires = 0 === $this->options['cookie_lifetime'] ? 0 : time() + $this->options['cookie_lifetime'];
        $cookie = $this->cookieFactory->create($this->options['cookie_name'], $value, $expires);

        $this->cookieRepository->persist($cookie);
    }

    public function erase(Request $request): void
    {
        if (!$request->cookies->has($name = $this->options['cookie_name'])) {
            return;
        }

        $cookie = $this->cookieFactory->create($name, null, -1);
        $this->cookieRepository->persist($cookie);
    }

    private function setOptions(array $options, string $queryParam): void
    {
        $this->options = array_merge(self::DEFAULT_OPTIONS, $options);

        if (null === $this->options['cookie_name']) {
            $this->options['cookie_name'] = \sprintf('izi_' . $queryParam);
        }
    }
}
